edition = "2024"

hard_tabs = false
tab_spaces = 2

max_width = 120

newline_style = "Unix"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true

fn_single_line = false
where_single_line = false

imports_granularity = "Crate"

trailing_comma = "Vertical"

wrap_comments = false
format_code_in_doc_comments = false
normalize_comments = false

format_strings = false
format_macro_matchers = true
format_macro_bodies = true
